### ISSUE TITLE
Bug: Param heading is wrong

### ISSUE THREAD

**Issue by Skatterbrainz** [Sycnex/Windows10Debloater#8] opened 2018-02-22 17:33 UTC
The Windows10Debloater.ps1 script appears to be missing a final closing "}" on the last function.

**Comment by Sycnex** [comment] 2018-02-23 13:57
Hi Skatterbrainz,

I cannot seem to reproduce this regardless of what I run. Can you please provide a screenshot if it is continuing to still happen?

**Comment by Sycnex** [comment] 2018-03-07 04:32
Any update on this? Otherwise if it works can I close this issue?

**Comment by Skatterbrainz** [comment] 2018-03-08 04:58
The issue is with having three param() blocks, it throws an error.  It should be one param() block with the [switch] params nested.

```
param([switch]$Debloat)

param([switch]$SysPrep)

param([switch]$StopEdgePDF)

```
should be...
```
param (

  [switch]$Debloat,

  [switch]$SysPrep,

  [switch]$StopEdgePDF

)
```
once I change that, everything appears to work fine.

**Comment by Skatterbrainz** [comment] 2018-03-12 19:29
Any update on this?

**Comment by Sycnex** [comment] 2018-03-12 19:30
Hi,

I haven't gotten a chance due to some personal life things going on. I will
update it today if I get the chance.

**Comment by Sycnex** [comment] 2018-03-16 04:28
This has been fixed as specified.

**Closed as completed by Sycnex** 2018-03-16 04:28 UTC
