### ISSUE TITLE
Bad comment. 

### ISSUE THREAD

**Issue by KurtisKiesel** [Sycnex/Windows10Debloater#94] opened 2019-02-26 13:13 UTC
There is a bad comment on line number 28.  The end of the multi line comment is just in the wrong place, borking the script. I would imagine it either should go on line 28 and then line 29 should be the end of the function. or it should be at the end of 16 or line 26 depending on what was intended. 

I was able to run the script successfully on a test box by putting it at the end of line 16, I could have just commented out line 16 I guess too, removing the multiline comment.

**Comment by Sycnex** [comment] 2019-03-04 07:17
Which script?

**Comment by KurtisKiesel** [comment] 2019-03-04 07:44
Sysprep

**Comment by smoonlee** [comment] 2019-03-11 15:48
@Sycnex  This can be closed - i created a PR with #100
Duplicate of #100

**Closed as completed** 2019-06-10 05:44 UTC
