### ISSUE TITLE
Errors running script with Win 10 v1803

### ISSUE THREAD

**Issue by xsisbest** [Sycnex/Windows10Debloater#30] opened 2018-06-14 02:07 UTC
Just wanted to post my experience with v1803 of Windows 10. Not to bad. Just a few. I see the top 2 are xbox related and the rest I'm uncertain of. I'll deploy again using a usb drive and pxe one more time to see if it's consistent. I used the -sysprep and -debloat parameters but not the edgepdf. It gave me issues on 1703.
![capture](https://user-images.githubusercontent.com/39020284/41387680-13c5e23a-6f3d-11e8-8b8b-d781c083cecc.PNG)

**Comment by charliefsilva** [comment] 2018-06-14 11:11
Also having this same errors in 1803 build when running this script in my task sequence. Running -sysprep and -debloat as well. What i can understand from LTI logs is that is something related with trying to override the default PDF application (perhaps edgepdf?) on the registry. 

edit: Manage to deploy debloated machine without issues! Had a closer look at the deployment logs and found that in line 167 the "Get-ScheduledTask -TaskName XblGameSaveTaskLogon | Disable-ScheduledTask -ErrorAction SilentlyContinue" fails because this task does not exist on 1803 Enterprise version. Added a comment to the line 243 "Stop-EdgePDF" as well and no errors were thrown again. I can live with having to change the default PDF viewer manually for now.

Awesome script, btw mate! Thanks Sycnex

**Comment by Sycnex** [comment] 2018-06-15 00:43
@xsisbest 

@charliefsilva is correct in that the Xbox errors are due to the scheduled tasks not existing on your OS.

Secondly, I the other errors are related to the "Stop-EdgePDF" function, and it is just saying that the properties of "NoOpenWith" don't exist. 

I'll add some better error handling shortly.

**Comment by xsisbest** [comment] 2018-06-15 02:59
I can do the same. It had no effect on my install and it debloated as stated. Best script I've found for taking out the trash!

**Comment by Keithk1227** [comment] 2018-06-27 20:59
I'm also having errors with 1803, though they are different than the other errors noted.  Any thoughts?

At C:\Build\Windows10SysPrepDebloater.ps1:134 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\Build\Windows10SysPrepDebloater.ps1:138 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\Build\Windows10SysPrepDebloater.ps1:143 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\Build\Windows10SysPrepDebloater.ps1:148 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\Build\Windows10SysPrepDebloater.ps1:152 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\Build\Windows10SysPrepDebloater.ps1:381 char:185
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in 
double quotation marks ("&") to pass it as part of a string.
At C:\Build\Windows10SysPrepDebloater.ps1:385 char:18
+ </form>          <h3 class="pt-2">Join GitHub today</h3>
+                  ~
The '<' operator is reserved for future use.
At C:\Build\Windows10SysPrepDebloater.ps1:542 char:11
+       241 lines (192 sloc)
+           ~~~~~
Unexpected token 'lines' in expression or statement.
At C:\Build\Windows10SysPrepDebloater.ps1:542 char:22
+       241 lines (192 sloc)
+                      ~~~~
Unexpected token 'sloc' in expression or statement.
At C:\Build\Windows10SysPrepDebloater.ps1:542 char:21
+       241 lines (192 sloc)
+                     ~
Missing closing ')' in expression.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

**Comment by Sycnex** [comment] 2018-06-30 04:22
Just curious, but did you run it as an Administrator, @Keithk1227 ?

**Comment by Keithk1227** [comment] 2018-06-30 22:20
Yes, I tried it running just PowerShell as admin and changing to the folder and running the app.  I also tried to run PowerShell ISE as admin, dropping the source code into it and running it from there.  I also tried it on 2 different systems, one that started with Feature update 1703 and I updated to 1803 and one that I built a new 1803 from scratch using the MVLS ISO.

**Comment by Sycnex** [comment] 2018-07-01 05:51
Can you also send me the log that is created from the script, located at:

C:\Windows10Debloater

**Comment by Keithk1227** [comment] 2018-07-02 15:39
Neither Windows10Debloater or Windows10SysPrepDebloater creates a log file in that location.  I also checked the user's and the Windows temp folders.  What is the actual file name so I can search for it.

**Comment by Sycnex** [comment] 2018-07-11 02:36
The Windows10Debloater does create a log file located at: C:\Windows10Debloater, and the file name typically starts with: PowerShell_transcript.

I just confirmed this on my machine.

**Closed as completed** 2018-07-15 10:22 UTC
