### ISSUE TITLE
Not uninstalling all junk apps

### ISSUE THREAD

**Issue by abulgatz** [Sycnex/Windows10Debloater#15] opened 2018-04-05 04:44 UTC
Recently seems to be leaving behind a lot of junk. Spotify, SketchBook, News, Candy Crush, Disney Magic, Minecraft, and a few others aren't being uninstalled.

Tested on a number of different computers with clean installs of the latest Windows 10 builds.

**Comment by Blu3ish** [comment] 2018-04-05 09:50
Hey Abulgatz,

Have you tried creating a new user?

It should be gone after that, it doesn’t work on existing users, it tries to uninstall but the problem isn’t the uninstalling but Windows 10 start menu. 

The only solution I am aware of is removing those apps from the Windows 10 start menu all current users manually, or recreate the user(s).

You might have succes if you enable the local administrator account, execute the script and disable it again thats how i do it.

**Comment by Sycnex** [comment] 2018-04-06 01:59
@Blu3ish is correct with everything they have said.

**Comment by Sycnex** [comment] 2018-04-14 06:48
@abulgatz May I close this?

**Comment by abulgatz** [comment] 2018-04-14 08:11
I'm still looking into this. It does seem to be a problem even with new accounts after the script is run, not just existing accounts.

**Comment by Sycnex** [comment] 2018-04-29 17:32
Interesting. Have you tried both scripts @abulgatz?

**Closed as completed** 2018-06-11 02:34 UTC
